CONTIKI_PROJECT = sensors-test
all: $(CONTIKI_PROJECT)

# Dedicated example to CC1310 LaunchPad
TARGET:=srf06-cc26xx
#BOARD := sensortag/cc1350
BOARD := wittratag/cc1350

PROJECT_SOURCEFILES += 

#MODULES += os/services/shell

#MAKE_MAC = MAKE_MAC_TSCH

CONTIKI = ../../..
include $(CONTIKI)/Makefile.include
