### Will allow the inclusion of the correct CPU makefile
CPU_FAMILY = cc26xxr2

### Add to the source dirs
CONTIKI_TARGET_DIRS += wittratag/cc2640r2

### Include the common wittratag makefile
include $(PLATFORM_ROOT_DIR)/wittratag/Makefile.wittratag
