CFLAGS += -DBOARD_WITTRATAG=1
CFLAGS += -DBACKDOOR_IOID=0x00000000

CONTIKI_TARGET_DIRS += wittratag common

BOARD_SOURCEFILES += wittratag-sensors.c board-buttons.c sensor-common.c
BOARD_SOURCEFILES += bmg-250-sensor.c xmem.c
BOARD_SOURCEFILES += board.c board-i2c.c

MODULES += arch/dev/ext-flash
